In [21]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import random
import math

In [22]:
data_c = pd.read_csv('train.csv')
data_test = pd.read_csv('test.csv')
df_c = pd.DataFrame(data_c)
df_t = pd.DataFrame(data_test)
l = len(df_c)
df_c = df_c.drop('id', 1)
df_c = df_c.drop('CARTYPE_03_CAT', 1)
df_c = df_c.drop('CARTYPE_05_CAT', 1)
df_t = df_t.drop('CARTYPE_03_CAT', 1)
df_t = df_t.drop('CARTYPE_05_CAT', 1)
y = df_c['target']
df_c = df_c.drop('target', 1)
id_1 = df_t['id']
df_t = df_t.drop('id', 1)

In [23]:
X_train = df_c
X_train = np.array(X_train)
X_train
X_test = df_t
X_test = np.array(X_test)
X_test
print(X_train.shape)

(297606, 55)


In [24]:
Y_train = np.array(y)
Y_train

array([1, 0, 0, ..., 0, 1, 0])

In [25]:
from sklearn.impute import SimpleImputer
imp1 = SimpleImputer(missing_values=np.nan, strategy='mean')
imp2 = SimpleImputer(missing_values=np.nan, strategy='mean')
imp1.fit(X_train)

SimpleImputer()

In [26]:
X_train = imp1.transform(X_train)
print(X_train)

[[ 1.  1. 21. ... 21.  0.  1.]
 [ 0.  1.  7. ... 35.  0.  0.]
 [ 1.  0. 21. ... 21.  0.  0.]
 ...
 [ 1.  0.  7. ...  7.  0.  0.]
 [ 1.  1. 21. ... 35.  0.  0.]
 [ 1.  0. 14. ... 56.  1.  1.]]


In [27]:
imp2.fit(X_test)

SimpleImputer()

In [28]:
X_test = imp2.transform(X_test)
print(X_test)

[[ 1.  0.  7. ... 14.  0.  0.]
 [ 1.  0. 14. ... 28.  1.  0.]
 [ 0.  0.  7. ... 35.  0.  0.]
 ...
 [ 1.  0. 21. ...  7.  1.  0.]
 [ 1.  0. 28. ...  7.  1.  1.]
 [ 0.  0.  7. ... 28.  0.  0.]]


In [29]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
scaler.fit(X_train)
X_train = scaler.transform(X_train)
X_test = scaler.transform(X_test)

In [30]:
from sklearn.linear_model import LogisticRegression
logistic = LogisticRegression(random_state = 0, max_iter = 1000, class_weight = "balanced")
l = logistic.fit(X_train, Y_train)
y_pred = l.predict_proba(X_test)
y_pred

array([[0.39452935, 0.60547065],
       [0.49444605, 0.50555395],
       [0.53285619, 0.46714381],
       ...,
       [0.443415  , 0.556585  ],
       [0.58704765, 0.41295235],
       [0.60925071, 0.39074929]])

In [33]:
result_df = pd.DataFrame(id_1, columns = ['id'])
result_df['target'] = y_pred[:,1] 
print(result_df)
count = 0
for i in range(len(df_t)):
    if(y_pred[i,1] == 1):
        count += 1
print(count)

            id    target
0            0  0.605471
1            1  0.505554
2            2  0.467144
3            3  0.385507
4            4  0.468510
...        ...       ...
297601  297601  0.504942
297602  297602  0.432330
297603  297603  0.556585
297604  297604  0.412952
297605  297605  0.390749

[297606 rows x 2 columns]
0


In [34]:
result_df.to_csv('submission_class_2.csv',index = False)